import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages"

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server"

export const onRequest = async (context: any) => {
  try {
    return await createPagesFunctionHandler({ build })(context)
  } catch (error) {
    console.error("Error in Cloudflare Pages Function:", error)
    return new Response("Internal Server Error", { status: 500 })
  }
}
